### ISSUE TITLE
error algemene zoek site

### ISSUE THREAD

**Issue by roxannewyns** [libis/Nabucco#16]
assigned @JorisLambrechts 

algemene zoekbox site

error bij zoekopdracht op 'The Babylonian expedition' (zie screen onder)
Als ik zoek op BE 9 (de short title van /items/show/97) krijg ik 0 resultaten.

![capture](https://cloud.githubusercontent.com/assets/3798589/6961172/2acb0260-d929-11e4-834f-2c11db51b2f6.JPG)

**Comment by JorisLambrechts** [comment]
op wat moet deze zoekopdracht zoeken? Alles of enkel items van een bepaald type?

**Comment by roxannewyns** [comment]
algemene zoek mag op alles zoeken. is al het geval denk ik.
