### ISSUE TITLE
opties voor table view

### ISSUE THREAD

**Issue by roxannewyns** [libis/Nabucco#33]
assigned  @JorisLambrechts 
Bekijk eens wat je hier kan doen. Niet te veel tijd in steken, is eerder op een idee te krijgen of alle metadata er dan opgeraakt.

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Nabucco/commit/724c6a6e9f50ea3bf42602a5b41585c2696166c6 en https://github.com/libis/Nabucco/commit/f9f4428b48b1b30087e7e0cc4e189b0755fe4865
