### ISSUE TITLE
sortering van de zoekresultaten

### ISSUE THREAD

**Issue by roxannewyns** [libis/Nabucco#34]
assigned @JorisLambrechts 

Op alle resultatenpagina's (dus ook bij people, archive etc) de sort optie "Date added" verwijderen. 

Toevoegen bij sorteren bij Catalogue: Archive, Julian date, Type & content. Bekijk wat je kan doen met die BCE dates. 

![capture](https://cloud.githubusercontent.com/assets/3798589/8652058/dcea147e-297c-11e5-81f0-9b6b89f004f7.JPG)

**Comment by JorisLambrechts** [comment]
eerste aanzet: https://github.com/libis/Nabucco/commit/d91b785cb9dcd7b33d00fa9b6955832fed9d36e3

Enkel sorteren of Julian date en Archive (is een relatie en geen metadataveld van een tablet, Place of issue is hetzelfde probleem) moet nog bekeken worden.

**Comment by roxannewyns** [comment]
Julian data belangrijkste. Archive kan wachten

**Comment by JorisLambrechts** [comment]
De sort in omeka werkt direct via een database query en kan er op dit moment ook niet via de julian date gesorteerd worden omdat die op verschillende manieren in de databank zit (met BCE en soms als interval).

We kunnen misschien wel het jaartal in een apart veld steken en daar op sorteren? Dat zit misschien al apart in collective access?

**Comment by roxannewyns** [comment]
Ik heb voor item type 'tablet' een nieuwe metadata veld 'Julian date year' aangemaakt om hier een apart jaartal in te importeren om vervolgens op te sorteren. 
Heb je enkel probleem met de BCE of ook met de slash (12/11/439 BCE)?

Voorlopig krijg ik het jaartal niet apart uit CollectiveAccess, maar misschien kan naeem dit doen in de mapping. Nog te door @aruijmen

**Comment by JorisLambrechts** [comment]
dit is al een tijdje in orde denk ik (https://github.com/libis/Nabucco/commit/07dae4a23891056ca713abc9b7caf589c15339f5)
