### ISSUE TITLE
opmaak catalogue browse item page

### ISSUE THREAD

**Issue by roxannewyns** [libis/Nabucco#35]
assigned @JorisLambrechts 

A. 
Nabucco No., Museum No., CDLI no. (= nieuw veld, zie onder) op 1 lijn zetten zoals voorbeeld Persons.

Period, Babylonian date,  Julian date op 1 lijn zetten zoals voorbeeld Persons.
Date remark eronder.

![capture](https://cloud.githubusercontent.com/assets/3798589/8652548/8a7c3bce-297f-11e5-86d7-5fdebb57ea59.JPG)

B. Nieuw veld tonen in front-end (reeds aangemaakt in back-end): 
CDLI No. (Volgorde: Naast Museum No., zie boven)
Photo (Volgorde: helemaal onderaan lijst) 

C. Niet tonen in front-end: 
Museum inv. 
Volume No.

**Comment by roxannewyns** [comment]
Kan je eventueel de bovenste 3 rijen dichter bijeen zetten? Nu nogal veel ruimte tussen Nabucco Nr., Period lijn en Date remark lijn. Kan je de kolom van de bovenste 2 rijenen ook iets meer op elkaar uitlijnen zodat bv. Julian date recht onder CDLI nummer staat?

![capture](https://cloud.githubusercontent.com/assets/3798589/8854235/42d39ea6-315f-11e5-97a3-74b3e21e55eb.JPG)

**Comment by roxannewyns** [comment]
Als ik een URL toevoeg naar een foto dan verschijnt deze. Nu vind ik dat niet slecht (al weet ik niet zeker dat het de bedoeling is), maar hij is wel nogal groot en back to search results zou eronder moeten komen.
![capture](https://cloud.githubusercontent.com/assets/3798589/8854422/17bcbc38-3160-11e5-9c7a-5dd0b9c20c50.JPG)

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Nabucco/issues/39 voor fix
