### ISSUE TITLE
Duplicate tonen in front-end

### ISSUE THREAD

**Issue by roxannewyns** [libis/Nabucco#50]
Waarde in het element 'Duplicate' (item type tablets) tonen in front-end.
Is er voor dit veld iets van relaties voorzien in je mapping script? Normaal zou dit een tablet-tablet relatie moeten zijn. Als die niet bestaat moet je die voorlopig niet toevoegen.

**Comment by roxannewyns** [comment]
test record: /items/show/id/7522

**Comment by JorisLambrechts** [comment]
De relatie wordt al gelegd dus dat is in orde, ik zal nu dan nog dit veld laten tonen als de relatie om de een of andere reden niet gevonden wordt.
