### ISSUE TITLE
Correct sorting of places

### ISSUE THREAD

**Issue by aruijmen** [libis/Nabucco#56]
Make sure the Places are also sorted correctly in Omeka. (see CA)
Of course a new sync will be necessary. Just let me know when.
They added  'Illegible', 'No Place' and 'Unknown place'.
(Time: 0.5d)

@JorisLambrechts

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Nabucco/commit/038201ca305e1b245f6df4cbc75263a8735b54a7
https://github.com/libis/Nabucco/commit/b525bcfe74fce4d282f7e2c6d680ca317c846290
