### ISSUE TITLE
sortering drop-down lijst 'Month' aanpassen

### ISSUE THREAD

**Issue by roxannewyns** [libis/Nabucco#60]
Sortering Romeinse cijfers momenteel alfabetisch, maar moet deze volgorde aannemen: I, II, III, IV, V, VI, VIb, VII, VIII, IX, X, XI, XII, XIIb

![image](https://user-images.githubusercontent.com/3798589/28010233-81cb8f30-655e-11e7-8e43-301ffbc76b7a.png)

**Comment by roxannewyns** [comment]
Nog niet in orde. Ik heb mijn cache leeggemaakt.

**Comment by roxannewyns** [comment]
OK, maar nu is de locatie van het zoekveld verschoven. Kan je dit terug boven other markings zetten? Nu staat het onderaan de lijst.

**Comment by JorisLambrechts** [comment]
Dat wordt moeilijk omdat de andere velden automatisch gegenereerd worden. Dit veld heb ik er uit moeten halen en manueel moeten vullen waardoor het dus niet langer tussen de andere in zit. 

Ik kan wel proberen om het alsnog er tussen te zetten maar dan moet de hele procedure weer herschreven worden.

**Comment by roxannewyns** [comment]
kan je het misschien helemaal bovenaan zetten? Indien niet, laat dan voorlopig maar. Ik zal zien wat ze zeggen.
