### ISSUE TITLE
'Bibliography (free text)' toevoegen

### ISSUE THREAD

**Issue by roxannewyns** [libis/Nabucco#61]
In front-end het veld bibliography publiceren.
Label = Bibliography (free text)
Toevoegen in Advanced search
![image](https://user-images.githubusercontent.com/3798589/31891867-e32972b4-b807-11e7-9c7c-e6b06b2a70b6.png)
In item detail onder 'Publication'
![image](https://user-images.githubusercontent.com/3798589/31891919-015703a0-b808-11e7-9b57-cf0929fcbeb8.png)

**Comment by roxannewyns** [comment]
vb. record: 35497

**Comment by JorisLambrechts** [comment]
Als ik het label wil veranderen in de search dan moet het ook in de databank veranderen en dus wsl ook in de data sync (tenzij dat op id gebeurd).

Ik zal Bibliography er voorlopig wel al inzetten en tot het ook aangepast is in de sync.

**Comment by roxannewyns** [comment]
cc @aruijmen Anita, kan jij dit bekijken voor de data sync
