### ISSUE TITLE
Data sycn issues

### ISSUE THREAD

**Issue by roxannewyns** [libis/Nabucco#62]
ca_objects.object_id: 8498 already existed in Omeka, yet another record was created

OLD: Item #7525
![image](https://user-images.githubusercontent.com/3798589/31892839-491d8dec-b80a-11e7-84e6-65ef24387b5f.png)

NEW: Item #35500
![image](https://user-images.githubusercontent.com/3798589/31892801-33fc10e6-b80a-11e7-99eb-42ac40d7cb2a.png)

**Comment by roxannewyns** [comment]
Multiple 'Philological notes' should be added on a new line instead of in the same field. In the example below in 3 repeated fields.
![image](https://user-images.githubusercontent.com/3798589/31892912-79828f64-b80a-11e7-9bea-7b345636e177.png)
![image](https://user-images.githubusercontent.com/3798589/31892971-964c0e90-b80a-11e7-8619-65e359d9b38f.png)

**Comment by aruijmen** [comment]
Hello Naeem,

I made the necessary changes to mappingrulesobjects.csv for the Philological notes and remarks to be put in separate fields.  The mapping file was replaced in CA.

**Comment by roxannewyns** [comment]
1st comment: To do Naeem
2nd comment: Done

**Comment by naeemmuhammad** [comment]
Sync works fine, it updates existing items.
