### ISSUE TITLE
Ontbrekende informatie op Tablet display

### ISSUE THREAD

**Issue by aruijmen** [libis/Nabucco#66]
In de 'less info' display ontbreekt momenteel het veld Bibliography.
In de 'more info' display ontbreekt momenteel het veld Seal

**Comment by JorisLambrechts** [comment]
Bibliography (free text)

**Comment by aruijmen** [comment]
veld Bibliography (free text) toegevoegd in Omeka. 
In mapping-file voor sync laten we voorlopig de info in beide velden (bibliography en bibliography (free text) toekomen.
